DROP TABLE IF EXISTS feedtimes;
DROP TABLE IF EXISTS feedlog;
DROP TABLE IF EXISTS users;

CREATE TABLE FEED_TIMES(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"time" TEXT,
	"size" TEXT
);

CREATE TABLE FEED_LOG(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"time" TEXT,
	"date" TEXT,
	"size" TEXT,
	"type" TEXT
);

CREATE TABLE USER_INFO(
	"user_id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"email" TEXT,
	"password" TEXT
);

INSERT INTO feedtimes ("id") VALUES (1),(2),(3)
