DROP TABLE IF EXISTS FEED_TIMES;
DROP TABLE IF EXISTS FEED_LOG;
DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE FEED_TIMES(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"time" TEXT,
	"size" TEXT
);

CREATE TABLE FEED_LOG(
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"time" TEXT,
	"date" TEXT,
	"size" TEXT,
	"type" TEXT
);

CREATE TABLE USER_INFO(
	"user_id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"email" TEXT,
	"password" TEXT
);